### PR TITLE
Use packit.Fail to indicate when this buildpack will not Detect

### LINKED ISSUE #27: Detect is unnecessarily noisy when pyproject.toml file does not exist
Detect should fail silently when `pyproject.toml` is not present. It should only display an error to the user when the file exists and there is an issue with it.

Example output of running detect against a non-poetry app:
```
======== Output: paketo-buildpacks/poetry@0.1.2 ========
pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies
err:  paketo-buildpacks/poetry@0.1.2 
```

Proposal:

* We should probably return an empty string and nil error from:
https://github.com/paketo-buildpacks/poetry/blob/4583111bf857b79ec07ef9fa77fa93538b680d4f/pyproject_parser.go#L30
* In `detect.go` we should return `packit.Fail` if there is no error and an empty string.

### PR DESCRIPTION
**Pull request by joshuatcasey**
## Summary
Resolves #27 

## Use Cases
Don't log messages when this buildpack can't find `pyproject.toml`. This is a perfectly normal scenario.

If there is a `pyproject.toml` without `tool.poetry.dependencies.python` then that's a user error and should be logged.

### Scenario: without `pyproject.toml`

```shell
===> DETECTING
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
```

### Scenario: with `pyproject.toml` and without `tool.poetry.dependencies.python`:
```shell
===> DETECTING
[detector] ======== Output: paketo-buildpacks/poetry@1.0.1 ========
[detector] pyproject.toml must include [tool.poetry.dependencies.python], see https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies
[detector] err:  paketo-buildpacks/poetry@1.0.1 (1)
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: failed to detect: buildpack(s) failed with err
```

### Scenario: with `pyproject.toml` and with `tool.poetry.dependencies.python`:
Using `pack -v`:

```shell
===> DETECTING
...
[detector] ======== Results ========
[detector] pass: paketo-buildpacks/poetry@1.0.1
[detector] Resolving plan... (try #1)
[detector] fail: paketo-buildpacks/poetry@1.0.1 requires pip
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
```

## Checklist
* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by joshuatcasey** [comment]
I'll admit the solution is a bit awkward. I think it's because `"poetry".PyProjectParser.ParsePythonVersion` has two purposes:

**Comment by robdimsdale** [comment]
@joshuatcasey thanks for putting this together!

I have a couple of thoughts:
1. I think it is more clear to move logic which determines if the `pyproject.toml` file exists (and hence the subsequent error handling) into the pyproject parser. That way the contract of the `ParsePythonVersion` method can be" "return empty string and nil error if file does not exist". I think that is cleaner than the current contract: "return error if file does not exist and force the caller to determine if the error is due to the file not existing or some other reason."
2. @thitch97 I believe you are correct in that `pyproject.toml` can be used by other python tools beyond poetry. However, we don't support that in any other of the python buildpacks. If there is evidence that consumers do in fact use `pyproject.toml` for non-poetry apps, then I would like to support that use-case. Until we get evidence of that, I would prefer to maintain the assumption that `pyproject.toml` is only used for poetry and therefore must contain the `tool.poetry.dependencies.python` section.
    * If we do expand support to other buildpacks for `pyproject.toml`, I think that would require a significant refactor of multiple buildpacks, including extracting out some common logic for parsing `pyproject.toml` and determining which toolchain (`poetry`, `pip`, etc) is described in that file. We would also have to handle the case where multiple tools are defined, as I believe that is also valid.
3. @joshuatcasey I agree that this PR isn't the place to separate the concerns of pyproject parser. If/when we decide to go down the path of more clearly delineating the concerns of determining if the file exists and parsing the python version, we should do it in a way that facilitates future expansion of `pyproject.toml` to other python toolchains (see my point above to Tim). I have some thoughts on what this might look like, but, again, I don't think we should explore that in this PR.

**Review by robdimsdale — CHANGES_REQUESTED** [review]
Can we move the logic of determining if the file exists inside the parser, returning `"",nil` if the file does not exist?

**Comment by joshuatcasey** [comment]
@robdimsdale Does this capture your intent? And of course I force-pushed, not realizing you had merged from main. :|

**Comment by robdimsdale** [comment]
@joshuatcasey 

> Does this capture your intent? 

Yes, thanks! I have a couple of minor tweaks and then I think this will be good to go.

**Review by robdimsdale — CHANGES_REQUESTED** [review]

File: detect.go [hunk 1]
```diff
@@ -22,11 +22,15 @@ type PyProjectPythonVersionParser interface {
...
 	return func(context packit.DetectContext) (packit.DetectResult, error) {
 		pythonVersion, err := parser.ParsePythonVersion(context.WorkingDir)
-
 		if err != nil {
+
 			return packit.DetectResult{}, err
 		}
 
+		if pythonVersion == "" {
+			return packit.DetectResult{}, packit.Fail.WithMessage("conditions not met for detection")
```
[the remark this answers is not in the document]
Comment (ryanmoran) [reply detect.go:31]: I think the preference here would be to add context. The point of this message is to help folks figure out why their app isn't detecting when they expect that it should. This message appears when you run `pack --verbose build some-app`:

```
===> DETECTING
======== Output: paketo-buildpacks/bundle-install@0.3.1 ========
Gemfile is not present
======== Output: paketo-buildpacks/yarn-install@0.7.1 ========
failed
======== Output: paketo-buildpacks/rails-assets@0.4.1 ========
failed to find assets in app/assets, app/javascript, lib/assets, or vendor/assets
======== Output: paketo-buildpacks/puma@0.2.1 ========
failed
======== Results ========
pass: paketo-buildpacks/ca-certificates@3.0.2
pass: paketo-buildpacks/mri@0.6.0
pass: paketo-buildpacks/bundler@0.3.1
fail: paketo-buildpacks/bundle-install@0.3.1
pass: paketo-buildpacks/node-engine@0.11.4
pass: paketo-buildpacks/yarn@0.5.1
skip: paketo-buildpacks/yarn-install@0.7.1
skip: paketo-buildpacks/rails-assets@0.4.1
fail: paketo-buildpacks/puma@0.2.1
skip: paketo-buildpacks/procfile@5.0.2
skip: paketo-buildpacks/environment-variables@4.0.2
skip: paketo-buildpacks/image-labels@4.0.2
```

As you can see, the messages coming from `bundle-install` and `rails-assets` are a bit more helpful than those coming from `yarn-install` or `puma`.

In cases where we don't have a message, its likely that the code predates the addition of the `WithMessage` option on the `packit.Fail` error type. I'd love to see those messages backfilled with useful context when we touch those parts of the codebase.

[the remark this answers is not in the document]
Comment (robdimsdale) [reply detect.go:31]: That's super helpful context - thanks @ryanmoran !

[the remark this answers is not in the document]
Comment (joshuatcasey) [reply detect.go:31]: Yeah. Ironically due to recent changes our `Detect` func doesn't know exactly why this buildpack isn't participating.

We could have a message `pyproject.toml is not present or it does not include python version`. 

Or we could have `ParsePythonVersion` return `packit.Fail.WithMessage` to indicate the specific issue. WDYT @robdimsdale ?

[the remark this answers is not in the document]
Comment (robdimsdale) [reply detect.go:31]: sigh. The irony is not lost on me!

Perhaps it is cleaner for `Detect` to first look for the `pyproject.toml` file with `fs.Exists()`, returning the error if it is not nil, and returning a `packit.Fail.WithMessage("pyproject.toml file does not exist")` if there is no error but also no file.

Then the `ParsePythonVersion` can instead take the path to the file, assume that the file exists, and not explicitly check for its existence before parsing it. If we keep the same contract - returning `"",nil` when the file can be successfully parsed but does not contain a python version, then we can clearly differentiate between the two valid failure modes (file does not exist / file does not contain python version) and any unexpected errors.

[the remark this answers is not in the document]
Comment (joshuatcasey) [reply detect.go]: See how things look now @robdimsdale . I rebased/squashed from latest `main`... the commit history wasn't helpful anyways.

File: detect_test.go [hunk 2]
```diff
@@ -93,33 +67,95 @@ func testDetect(t *testing.T, context spec.G, it spec.S) {
...
+						},
+					},
+				}))
+			})
+		})
+
+		context("error handling", func() {
+			// the python dependency is mandatory
+			// https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies
+			it("fails detection when no python version found", func() {
```
Comment (robdimsdale) [inline detect_test.go:132]: The pattern I've seen for other buildpacks is to consider correctly-failing detection as a happy-path rather than an error case. So we would move it up to the section above rather than having it under the error handling context.

File: detect_test.go [hunk 3]
```diff
@@ -93,33 +67,95 @@ func testDetect(t *testing.T, context spec.G, it spec.S) {
...
+	})
+
+	context("when pyproject.toml is not present", func() {
+		it("fails detection", func() {
+			_, err := detect(packit.DetectContext{
+				WorkingDir: workingDir,
 			})
-			Expect(result).To(Equal(packit.DetectResult{}))
-			Expect(err).To(Equal(expectedErr))
+			Expect(err).To(MatchError("pyproject.toml is not present"))
```
Comment (robdimsdale) [inline detect_test.go:158]: Similar to the previous comment, I would move this to the happy-path section. I'd also validate the specific error is `packit.Fail` rather than the more general assertion we see here.

File: init_test.go [hunk 4]
```diff
@@ -10,7 +10,7 @@ import (
 func TestUnit(t *testing.T) {
 	suite := spec.New("poetry", spec.Report(report.Terminal{}), spec.Parallel())
 	suite("Build", testBuild)
-	suite("Detect", testDetect)
+	suite("Detect", testDetect, spec.Sequential())
```
Comment (robdimsdale) [inline init_test.go:13]: Do we have to run the tests in order? I'm surprised to see the `spec.Sequential()` in unit tests.

**Review by robdimsdale — APPROVED** [review]
I'm happy to merge this now. There's a couple of small issues - mostly pertaining to the tests - but I'd be happy to address those at a later date.

File: init_test.go (hunk 4 above)
Comment (joshuatcasey) [reply init_test.go:13]: The original test called out `spec.Sequential()`. I tried removing it but the tests failed, I suspect because the test is manipulating the environment variables.

File: detect_test.go (hunk 3 above)
Comment (joshuatcasey) [reply detect_test.go:158]: @robdimsdale do you have an example of how to validate that specific error? I tried a few permutations without success.

Comment (joshuatcasey) [reply detect_test.go:158]: This context should already be at the top level. The context for `error handling` is in another context.

File: init_test.go (hunk 4 above)
Comment (robdimsdale) [reply init_test.go:13]: Ok, we can keep this for now and investigate after we merge.

File: detect_test.go (hunk 3 above)
Comment (robdimsdale) [reply detect_test.go:158]: I was thinking of doing something similar to what we see above e.g.:

```
Expect(err).To(MatchError(packit.Fail.WithMessage("pyproject.toml file is not present")))
```

File: init_test.go (hunk 4 above)
Comment (thitch97) [reply init_test.go:13]: Can confirm this is an issue we've seen across buildpacks and as far as we can tell does pertain to the manipulation of environment variables.

Comment (robdimsdale) [reply init_test.go:13]: Yes, I realized that after I wrote my comment.

File: detect_test.go (hunk 3 above)
Comment (robdimsdale) [reply detect_test.go:158]: As discussed, we can modify this at a later date.

File: detect_test.go (hunk 2 above)
Comment (robdimsdale) [reply detect_test.go:132]: As discussed, we can modify this at a later date.
